// Hashemite University IT Major Courses Data (CS, CIS, SWE, BIT, CYS, AIDS)
const IT_MAJORS = {
  'AIDS': {
    name: 'Artificial Intelligence & Data Science',
    courses: [
      { id: 'aids_prog', name: 'Introduction to Programming', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'aids_prog_lab', name: 'Introduction to Programming Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'aids_oop', name: 'Object Oriented Programming (Java 1)', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Programming' },
      { id: 'aids_oop_lab', name: 'Object Oriented Programming Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Object Oriented Programming (Java 1)' },
      { id: 'aids_ds', name: 'Data Structures', credits: 3, difficulty: 'Hard', prerequisite: 'Object Oriented Programming (Java 1)' },
      { id: 'aids_algo', name: 'Algorithms Analysis and Design', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'aids_web', name: 'Web Applications Programming', credits: 3, difficulty: 'Medium', prerequisite: 'Object Oriented Programming (Java 1)' },
      { id: 'aids_swe', name: 'Software Engineering Fundamentals', credits: 3, difficulty: 'Medium', prerequisite: 'Object Oriented Programming (Java 1)' },
      { id: 'aids_db', name: 'Introduction to Database Systems', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'aids_db_lab', name: 'Database Systems Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Database Systems' },
      { id: 'aids_discrete', name: 'Discrete Mathematics', credits: 3, difficulty: 'Hard', prerequisite: 'None' },
      { id: 'aids_logic', name: 'Digital Logic Design', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'aids_comp_sys', name: 'Computing Systems for Data Science & AI', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'aids_fund_ds', name: 'Fundamentals of Data Science', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'aids_fund_ai', name: 'Fundamentals of Artificial Intelligence', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'aids_ml', name: 'Machine Learning', credits: 3, difficulty: 'Hard', prerequisite: 'Fundamentals of Artificial Intelligence' },
      { id: 'aids_dl', name: 'Neural Networks & Deep Learning', credits: 3, difficulty: 'Hard', prerequisite: 'Machine Learning' },
      { id: 'aids_adv_prog', name: 'Advanced Programming for AI & Data Science', credits: 3, difficulty: 'Medium', prerequisite: 'Object Oriented Programming (Java 1)' },
      { id: 'aids_img_proc', name: 'Digital Image Processing', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'aids_ir', name: 'Information Retrieval', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Database Systems' },
      { id: 'aids_cloud', name: 'Cloud Computing', credits: 3, difficulty: 'Medium', prerequisite: 'Computing Systems for Data Science & AI' },
      { id: 'aids_mining', name: 'Data Mining', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Database Systems' },
      { id: 'aids_adv_db', name: 'Advanced Database Systems', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Database Systems' },
      { id: 'aids_dwh', name: 'Data Warehousing Technology', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Database Systems' },
      { id: 'aids_bigdata', name: 'Big Data', credits: 3, difficulty: 'Hard', prerequisite: 'Fundamentals of Data Science' },
      { id: 'aids_analytics', name: 'Data Engineering and Analytics', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Data Science' },
      { id: 'aids_security', name: 'Data Security and Privacy', credits: 3, difficulty: 'Medium', prerequisite: 'Computing Systems for Data Science & AI' },
      { id: 'aids_tools', name: 'Data Science Tools', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Data Science' },
      { id: 'aids_hpc', name: 'High Performance Computing', credits: 3, difficulty: 'Hard', prerequisite: 'Computing Systems for Data Science & AI' },
      { id: 'aids_robotics', name: 'Smart Mobile Robotics', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Artificial Intelligence' },
      { id: 'aids_robot_prog', name: 'Robot Programming', credits: 3, difficulty: 'Medium', prerequisite: 'Smart Mobile Robotics' },
      { id: 'aids_nlp', name: 'Natural Language Processing & Text Mining', credits: 3, difficulty: 'Hard', prerequisite: 'Machine Learning' },
      { id: 'aids_time_series', name: 'Time Series Analysis', credits: 3, difficulty: 'Medium', prerequisite: 'Principles of Statistics' },
      { id: 'aids_vision', name: 'Computer Vision', credits: 3, difficulty: 'Hard', prerequisite: 'Digital Image Processing' },
      { id: 'aids_cities', name: 'Smart Cities', credits: 3, difficulty: 'Easy', prerequisite: 'Fundamentals of Data Science' },
      { id: 'aids_special', name: 'Special Topics in Data Science & AI', credits: 3, difficulty: 'Medium', prerequisite: 'Department Approval' },
      { id: 'aids_calc1', name: 'Calculus 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'aids_stats', name: 'Principles of Statistics', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'aids_linear', name: 'Linear Algebra 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'aids_biz_analytics', name: 'Business Data Analytics', credits: 3, difficulty: 'Medium', prerequisite: 'Principles of Statistics' },
      { id: 'aids_research', name: 'Scientific Research Methodology in IT', credits: 3, difficulty: 'Easy', prerequisite: 'Passed 80 Hours' },
      { id: 'aids_training', name: 'Field Training', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'aids_gp1', name: 'Graduation Project 1', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'aids_gp2', name: 'Graduation Project 2', credits: 3, difficulty: 'Hard', prerequisite: 'Graduation Project 1' }
    ]
  },
  'CS': {
    name: 'Computer Science',
    courses: [
      { id: 'cs_cpp', name: 'Introduction to Programming (C++)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_cpp_lab', name: 'Programming Lab (C++)', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1', name: 'Object-Oriented Programming 1', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1_lab', name: 'OOP 1 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2', name: 'Object-Oriented Programming 2', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2_lab', name: 'OOP 2 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cs_vb', name: 'Visual Programming (VB)', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_vb_lab', name: 'Visual Programming Lab (VB)', credits: 1, difficulty: 'Medium', prerequisite: 'Visual Programming' },
      { id: 'cs_web', name: 'Web Application Programming', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_ds', name: 'Data Structures', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_swe', name: 'Fundamentals of Software Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_multimedia', name: 'Multimedia Programming', credits: 3, difficulty: 'Easy', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_ai', name: 'Artificial Intelligence', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_db', name: 'Introduction to Databases', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_db_lab', name: 'Database Systems Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cs_simulation', name: 'Simulation Methods', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_graphics', name: 'Computer Graphics', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_algo', name: 'Analysis of Algorithms', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_mining', name: 'Data Mining', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Databases' },
      { id: 'cs_analysis', name: 'Systems Analysis and Design', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cs_security_cis', name: 'Information Systems Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_mobile', name: 'Mobile Application Development', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cs_gui', name: 'User Interface Design & Implementation (GUI)', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cs_pl', name: 'Programming Languages Design', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cs_discrete', name: 'Discrete Mathematics', credits: 3, difficulty: 'Hard', prerequisite: 'None' },
      { id: 'cs_logic', name: 'Digital Logic Design', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'cs_theory', name: 'Theory of Computation', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'cs_org', name: 'Computer Organization & Design', credits: 3, difficulty: 'Hard', prerequisite: 'Digital Logic Design' },
      { id: 'cs_architecture', name: 'Computer Architecture', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Organization' },
      { id: 'cs_os', name: 'Operating Systems Principles', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Organization' },
      { id: 'cs_networks', name: 'Computer Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Operating Systems Principles' },
      { id: 'cs_parallel', name: 'Parallel & Distributed Computing', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_wireless', name: 'Wireless Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_net_security', name: 'Network Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_protocols', name: 'Internet Protocols', credits: 3, difficulty: 'Medium', prerequisite: 'Computer Networks' },
      { id: 'cs_gp1', name: 'Graduation Project 1', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cs_gp2', name: 'Graduation Project 2', credits: 3, difficulty: 'Hard', prerequisite: 'Graduation Project 1' },
      { id: 'cs_training', name: 'Field Training', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cs_special', name: 'Special Topics in Computer Science', credits: 3, difficulty: 'Medium', prerequisite: 'Department Approval' },
      { id: 'math_calc1', name: 'Calculus 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_calc2', name: 'Calculus 2', credits: 3, difficulty: 'Hard', prerequisite: 'Calculus 1' },
      { id: 'cs_phys1', name: 'General Physics 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_phys1_lab', name: 'General Physics 1 Lab', credits: 1, difficulty: 'Medium', prerequisite: 'General Physics 1' },
      { id: 'cs_phys2', name: 'General Physics 2', credits: 3, difficulty: 'Hard', prerequisite: 'General Physics 1' },
      { id: 'math_linear', name: 'Linear Algebra 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_numerical', name: 'Numerical Analysis', credits: 3, difficulty: 'Hard', prerequisite: 'Calculus 2' },
      { id: 'math_stats', name: 'Applied Statistics & Probability', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_or', name: 'Operations Research', credits: 3, difficulty: 'Hard', prerequisite: 'Linear Algebra 1' }
    ]
  },
  'CIS': {
    name: 'Computer Information Systems',
    courses: [
      { id: 'cs_cpp', name: 'Introduction to Programming (C++)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_cpp_lab', name: 'Programming Lab (C++)', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1', name: 'Object-Oriented Programming 1', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1_lab', name: 'OOP 1 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2', name: 'Object-Oriented Programming 2', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2_lab', name: 'OOP 2 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cs_web', name: 'Web Application Programming', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_gui', name: 'User Interface Design & Implementation (GUI)', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cis_ecommerce', name: 'E-Commerce', credits: 3, difficulty: 'Medium', prerequisite: 'Web Application Programming' },
      { id: 'cis_web_adv', name: 'Advanced Web Application Programming', credits: 3, difficulty: 'Hard', prerequisite: 'Web Application Programming' },
      { id: 'cs_swe', name: 'Fundamentals of Software Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_vb', name: 'Visual Programming (VB)', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_vb_lab', name: 'Visual Programming Lab (VB)', credits: 1, difficulty: 'Medium', prerequisite: 'Visual Programming' },
      { id: 'cis_uml', name: 'Object-Oriented Software Development (UML)', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'cis_spm', name: 'Software Project Management (SPM)', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'cs_ds', name: 'Data Structures', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_algo', name: 'Analysis of Algorithms', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_mining', name: 'Data Mining', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Databases' },
      { id: 'cs_ai', name: 'Artificial Intelligence', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_multimedia', name: 'Multimedia Programming', credits: 3, difficulty: 'Easy', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_db', name: 'Introduction to Databases', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_db_lab', name: 'Database Systems Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cs_analysis', name: 'Systems Analysis and Design', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cis_db_adv', name: 'Advanced Database Systems', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Databases' },
      { id: 'cis_mis', name: 'Management Information Systems (MIS)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cis_warehouse', name: 'Data Warehousing Technology', credits: 3, difficulty: 'Hard', prerequisite: 'Advanced Database Systems' },
      { id: 'cis_its', name: 'Information Technology Systems (ITS)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_security_cis', name: 'Information Systems Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cis_ir', name: 'Information Retrieval Systems (IR)', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_discrete', name: 'Discrete Mathematics', credits: 3, difficulty: 'Hard', prerequisite: 'None' },
      { id: 'cs_logic', name: 'Digital Logic Design', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'cs_org', name: 'Computer Organization & Design', credits: 3, difficulty: 'Hard', prerequisite: 'Digital Logic Design' },
      { id: 'cs_networks', name: 'Computer Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Operating Systems Principles' },
      { id: 'cs_os', name: 'Operating Systems Principles', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Organization' },
      { id: 'cs_net_security', name: 'Network Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_wireless', name: 'Wireless Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_protocols', name: 'Internet Protocols', credits: 3, difficulty: 'Medium', prerequisite: 'Computer Networks' },
      { id: 'cs_gp1', name: 'Graduation Project 1', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cs_gp2', name: 'Graduation Project 2', credits: 3, difficulty: 'Hard', prerequisite: 'Graduation Project 1' },
      { id: 'cs_training', name: 'Field Training', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cis_special', name: 'Special Topics in CIS', credits: 3, difficulty: 'Medium', prerequisite: 'Department Approval' },
      { id: 'math_calc1', name: 'Calculus 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_stats', name: 'Applied Statistics & Probability', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'bus_mgmt1', name: 'Principles of Management 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'acc_acct1', name: 'Principles of Accounting 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'fin_finance', name: 'Principles of Finance', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cis_micro', name: 'Principles of Microeconomics', credits: 3, difficulty: 'None' }
    ]
  },
  'SWE': {
    name: 'Software Engineering',
    courses: [
      { id: 'cs_cpp', name: 'Introduction to Programming (C++)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_cpp_lab', name: 'Programming Lab (C++)', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1', name: 'Object-Oriented Programming 1', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1_lab', name: 'OOP 1 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2', name: 'Object-Oriented Programming 2', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2_lab', name: 'OOP 2 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'swe_java_adv', name: 'Advanced Java Programming', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'swe_vp', name: 'Visual Programming for Software Engineering (VP)', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_gui', name: 'User Interface Design & Implementation (GUI)', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cs_mobile', name: 'Mobile Application Development', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 2' },
      { id: 'cs_swe', name: 'Fundamentals of Software Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'swe_web_eng', name: 'Web Application Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'swe_ethics', name: 'Software Ethics & Security', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_spm', name: 'Software Project Management (SPM)', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_uml', name: 'Object-Oriented Software Development (UML)', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_doc', name: 'Software Documentation & Technical Writing', credits: 3, difficulty: 'Easy', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_design', name: 'Software Architecture & Design', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Software Development (UML)' },
      { id: 'swe_quality', name: 'Software Quality Assurance (SQA)', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_maint', name: 'Software Maintenance', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_testing', name: 'Software Testing', credits: 3, difficulty: 'Hard', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_req', name: 'Requirements Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_measure', name: 'Software Measurement & Metrics', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'cs_ds', name: 'Data Structures', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_algo', name: 'Analysis of Algorithms', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_db', name: 'Introduction to Databases', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_db_lab', name: 'Database Systems Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cs_analysis', name: 'Systems Analysis and Design', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'swe_cloud', name: 'Cloud Computing Applications', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'swe_data_ai', name: 'Data Science & Artificial Intelligence', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_discrete', name: 'Discrete Mathematics', credits: 3, difficulty: 'Hard', prerequisite: 'None' },
      { id: 'cs_logic', name: 'Digital Logic Design', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'cs_os', name: 'Operating Systems Principles', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Organization & Design' },
      { id: 'cs_networks', name: 'Computer Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Operating Systems Principles' },
      { id: 'cs_org', name: 'Computer Organization & Design', credits: 3, difficulty: 'Hard', prerequisite: 'Digital Logic Design' },
      { id: 'swe_iot', name: 'Internet of Things & IoT Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_gp1', name: 'Graduation Project 1', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cs_gp2', name: 'Graduation Project 2', credits: 3, difficulty: 'Hard', prerequisite: 'Graduation Project 1' },
      { id: 'cs_training', name: 'Field Training', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'swe_special', name: 'Special Topics in Software Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Department Approval' },
      { id: 'math_stats', name: 'Applied Statistics & Probability', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_calc1', name: 'Calculus 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_numerical', name: 'Numerical Analysis', credits: 3, difficulty: 'Hard', prerequisite: 'Calculus 2' },
      { id: 'math_linear', name: 'Linear Algebra 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' }
    ]
  },
  'BIT': {
    name: 'Business Information Technology',
    courses: [
      { id: 'cs_cpp', name: 'Introduction to Programming (C++)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_cpp_lab', name: 'Programming Lab (C++)', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1', name: 'Object-Oriented Programming 1', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1_lab', name: 'OOP 1 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2', name: 'Object-Oriented Programming 2', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_swe', name: 'Fundamentals of Software Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'bit_spm', name: 'Software Project Management (SPM)', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'cs_vp', name: 'Visual Programming', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_web', name: 'Web Application Programming', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cis_web_adv', name: 'Advanced Web Application Programming', credits: 3, difficulty: 'Hard', prerequisite: 'Web Application Programming' },
      { id: 'bit_emarketing', name: 'E-Marketing', credits: 3, difficulty: 'Medium', prerequisite: 'Web Application Programming' },
      { id: 'bit_eservices', name: 'E-Services', credits: 3, difficulty: 'Medium', prerequisite: 'Web Application Programming' },
      { id: 'bit_ecommerce', name: 'E-Commerce Applications', credits: 3, difficulty: 'Medium', prerequisite: 'Web Application Programming' },
      { id: 'bit_security', name: 'Information Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'bit_knowledge', name: 'Knowledge Management Systems', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'bit_dss', name: 'Decision Support Systems (DSS)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_ds', name: 'Data Structures', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_simulation', name: 'Simulation Methods', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_db', name: 'Introduction to Databases', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_db_lab', name: 'Database Systems Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cis_db_adv', name: 'Advanced Database Systems', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Databases' },
      { id: 'bit_mis', name: 'Management Information Systems (MIS)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_analysis', name: 'Systems Analysis and Design', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'bit_cloud', name: 'Cloud Computing for Business', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'cs_mining', name: 'Data Mining', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Databases' },
      { id: 'bit_sme', name: 'Systems for Small & Medium Enterprises (SMEs)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'bit_db_admin', name: 'Business Database Management & Administration', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Databases' },
      { id: 'bit_ai_bus', name: 'AI Applications in Business', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'bit_bi', name: 'Business Intelligence', credits: 3, difficulty: 'Hard', prerequisite: 'Business Database Management & Administration' },
      { id: 'bit_erp', name: 'Enterprise Resource Planning (ERP)', credits: 3, difficulty: 'Medium', prerequisite: 'Management Information Systems (MIS)' },
      { id: 'cs_discrete', name: 'Discrete Mathematics', credits: 3, difficulty: 'Hard', prerequisite: 'None' },
      { id: 'cs_logic', name: 'Digital Logic Design', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'cs_networks', name: 'Computer Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Operating Systems Principles' },
      { id: 'cs_net_security', name: 'Network Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_wireless', name: 'Wireless Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_gp1', name: 'Graduation Project 1', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cs_gp2', name: 'Graduation Project 2', credits: 3, difficulty: 'Hard', prerequisite: 'Graduation Project 1' },
      { id: 'cs_training', name: 'Field Training', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'bit_special', name: 'Special Topics in BIT', credits: 3, difficulty: 'Medium', prerequisite: 'Department Approval' },
      { id: 'bit_research', name: 'Research Methodology for IT', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_linear', name: 'Linear Algebra 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_calc1', name: 'Calculus 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'acc_acct1', name: 'Principles of Accounting 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'bus_mgmt1', name: 'Principles of Management 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_stats', name: 'Applied Statistics & Probability', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'bit_data_analysis', name: 'Business Data Analysis', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'fin_finance', name: 'Principles of Finance', credits: 3, difficulty: 'Medium', prerequisite: 'None' }
    ]
  },
  'CYS': {
    name: 'Cyber Security',
    courses: [
      { id: 'cs_cpp', name: 'Introduction to Programming (C++)', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'cs_cpp_lab', name: 'Programming Lab (C++)', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1', name: 'Object-Oriented Programming 1', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Programming' },
      { id: 'cs_java1_lab', name: 'OOP 1 Lab (Java)', credits: 1, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_java2', name: 'Object-Oriented Programming 2', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cys_web', name: 'Web Application Programming', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cys_web_lab', name: 'Web Application Programming Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Web Application Programming' },
      { id: 'cys_python', name: 'Python Programming for Security', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Programming' },
      { id: 'cis_web_adv', name: 'Advanced Web Application Programming', credits: 3, difficulty: 'Hard', prerequisite: 'Web Application Programming' },
      { id: 'cs_swe', name: 'Fundamentals of Software Engineering', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cys_spm', name: 'Software Project Management (SPM)', credits: 3, difficulty: 'Medium', prerequisite: 'Fundamentals of Software Engineering' },
      { id: 'cs_vb', name: 'Visual Programming (VB)', credits: 3, difficulty: 'Medium', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_vb_lab', name: 'Visual Programming Lab (VB)', credits: 1, difficulty: 'Medium', prerequisite: 'Visual Programming' },
      { id: 'cys_cys_principles', name: 'Cyber Security Principles', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Programming' },
      { id: 'cs_algo', name: 'Analysis of Algorithms', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_ai', name: 'Artificial Intelligence', credits: 3, difficulty: 'Hard', prerequisite: 'Data Structures' },
      { id: 'cs_db', name: 'Introduction to Databases', credits: 3, difficulty: 'Medium', prerequisite: 'Data Structures' },
      { id: 'cs_db_lab', name: 'Database Systems Lab', credits: 1, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cs_ds', name: 'Data Structures', credits: 3, difficulty: 'Hard', prerequisite: 'Object-Oriented Programming 1' },
      { id: 'cs_security_cis', name: 'Information Systems Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cys_hacking', name: 'Ethical Hacking', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cys_hacking_lab', name: 'Ethical Hacking Lab', credits: 1, difficulty: 'Hard', prerequisite: 'Ethical Hacking' },
      { id: 'cys_protocols', name: 'Information Security Protocols', credits: 3, difficulty: 'Hard', prerequisite: 'Information Systems Security' },
      { id: 'cys_malware', name: 'Malware Analysis', credits: 3, difficulty: 'Hard', prerequisite: 'Information Systems Security' },
      { id: 'cys_crypto', name: 'Introduction to Cryptography', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'cys_net_monitor', name: 'Network Monitoring & Administration', credits: 3, difficulty: 'Medium', prerequisite: 'Computer Networks' },
      { id: 'cys_ecommerce_sec', name: 'E-Commerce Security', credits: 3, difficulty: 'Medium', prerequisite: 'Web Application Programming' },
      { id: 'cys_stego', name: 'Information Hiding Techniques', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Cryptography' },
      { id: 'cys_forensics', name: 'Digital Forensics', credits: 3, difficulty: 'Hard', prerequisite: 'Information Systems Security' },
      { id: 'cys_forensics_lab', name: 'Digital Forensics Lab', credits: 1, difficulty: 'Hard', prerequisite: 'Digital Forensics' },
      { id: 'cs_analysis', name: 'Systems Analysis and Design', credits: 3, difficulty: 'Medium', prerequisite: 'Introduction to Databases' },
      { id: 'cys_db_sec', name: 'Database Security & Administration', credits: 3, difficulty: 'Hard', prerequisite: 'Introduction to Databases' },
      { id: 'cs_discrete', name: 'Discrete Mathematics', credits: 3, difficulty: 'Hard', prerequisite: 'None' },
      { id: 'cs_logic', name: 'Digital Logic Design', credits: 3, difficulty: 'Hard', prerequisite: 'Discrete Mathematics' },
      { id: 'cs_networks', name: 'Computer Networks', credits: 3, difficulty: 'Hard', prerequisite: 'Operating Systems Principles' },
      { id: 'cs_os', name: 'Operating Systems Principles', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Organization & Design' },
      { id: 'cs_org', name: 'Computer Organization & Design', credits: 3, difficulty: 'Hard', prerequisite: 'Digital Logic Design' },
      { id: 'cs_protocols', name: 'Internet Protocols', credits: 3, difficulty: 'Medium', prerequisite: 'Computer Networks' },
      { id: 'cys_net_threats', name: 'Network Security & Threats', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cys_cloud_sec', name: 'Cloud Security', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cys_ids', name: 'Protection Against Intrusion (IDS/IPS)', credits: 3, difficulty: 'Hard', prerequisite: 'Computer Networks' },
      { id: 'cs_gp1', name: 'Graduation Project 1', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cs_gp2', name: 'Graduation Project 2', credits: 3, difficulty: 'Hard', prerequisite: 'Graduation Project 1' },
      { id: 'cs_training', name: 'Field Training', credits: 3, difficulty: 'Medium', prerequisite: 'Passed 80 Hours' },
      { id: 'cys_special', name: 'Special Topics in Cyber Security', credits: 3, difficulty: 'Medium', prerequisite: 'Department Approval' },
      { id: 'math_linear', name: 'Linear Algebra 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_calc1', name: 'Calculus 1', credits: 3, difficulty: 'Medium', prerequisite: 'None' },
      { id: 'math_stats', name: 'Applied Statistics & Probability', credits: 3, difficulty: 'Medium', prerequisite: 'None' }
    ]
  }
};

window.TEST_BANK_QUESTIONS = {
  'cs_ds': [
    { q: "What is the time complexity of searching in a balanced Binary Search Tree (BST) in the worst case?", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], correct: 1, explanation: "A balanced Binary Search Tree has a height of log n. Therefore, searching, insertion, and deletion operations take O(log n) time." },
    { q: "Which data structure works based on the Last-In First-Out (LIFO) principle?", options: ["Queue", "Stack", "Heap", "Linked List"], correct: 1, explanation: "A Stack utilizes Last-In First-Out (LIFO), whereas a Queue operates on First-In First-Out (FIFO)." },
    { q: "What is the worst-case time complexity of the Quick Sort algorithm?", options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], correct: 2, explanation: "The worst case of Quick Sort occurs when the pivot partition is highly unbalanced, leading to O(n^2) comparisons." },
    { q: "In a Queue data structure, insertion is performed at the:", options: ["Rear", "Front", "Middle", "Any index"], correct: 0, explanation: "In a standard queue, elements are inserted (enqueued) at the Rear and removed (dequeued) from the Front." },
    { q: "Which of the following data structures is typically used to implement Depth-First Search (DFS) on a graph?", options: ["Stack", "Queue", "Binary Tree", "Hash Table"], correct: 0, explanation: "DFS uses a Stack (either the call stack recursively or an explicit stack object)." }
  ],
  'cs_cpp': [
    { q: "Which operator is used to release dynamically allocated memory on the heap in C++?", options: ["free()", "delete", "remove", "destruct"], correct: 1, explanation: "In C++, the 'delete' keyword is used to deallocate dynamic heap memory allocated with 'new'." },
    { q: "What is a pointer in C++?", options: ["A function that returns values", "A variable that stores the memory address of another variable", "An array index counter", "A reserve memory location"], correct: 1, explanation: "A pointer is a data type that holds the memory address of another variable as its value." },
    { q: "How do you declare a read-only variable (constant) in C++?", options: ["const", "constant", "define", "immutable"], correct: 0, explanation: "The 'const' keyword is prepended to a variable declaration in C++ to make its value read-only." },
    { q: "What is the typical memory size of a standard 'char' data type in C++?", options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"], correct: 0, explanation: "A standard 'char' character type takes exactly 1 byte (8 bits) of memory in C++." },
    { q: "Which header file is required to use the standard input/output streams 'cin' and 'cout'?", options: ["iostream", "stdio.h", "conio.h", "math.h"], correct: 0, explanation: "The standard header '<iostream>' provides functions for console input and output streams." }
  ],
  'cs_db': [
    { q: "Which Normal Form is specifically designed to address and eliminate multi-valued dependencies?", options: ["First Normal Form (1NF)", "Second Normal Form (2NF)", "Third Normal Form (3NF)", "Fourth Normal Form (4NF)"], correct: 3, explanation: "A relation is in 4NF if it is in BCNF and has no multi-valued dependencies." },
    { q: "What do the letters in the 'ACID' properties of transaction management represent?", options: ["Atomicity, Consistency, Isolation, Durability", "Atomicity, Continuity, Integrity, Database", "Access, Control, Identity, Delivery", "Authentication, Cryptography, Integrity, Decryption"], correct: 0, explanation: "ACID stands for Atomicity, Consistency, Isolation, and Durability." },
    { q: "Which SQL constraint uniquely identifies each record in a table and cannot contain NULL values?", options: ["Unique Key", "Primary Key", "Foreign Key", "Default Value"], correct: 1, explanation: "A Primary Key uniquely identifies a record. Unlike a Unique Key constraint, it cannot contain any NULL values." },
    { q: "What is the primary purpose of a Foreign Key constraint in databases?", options: ["To encrypt sensitive table data", "To index records for faster lookup", "To reference the Primary Key of another table to establish relation", "To create virtual duplicate tables"], correct: 2, explanation: "A Foreign Key establishes reference links between tables." },
    { q: "Which SQL command deletes all rows from a table without logging individual row deletions, preserving the table structure?", options: ["DROP", "DELETE", "TRUNCATE", "REMOVE"], correct: 2, explanation: "TRUNCATE quickly removes all rows from a table without deleting the schema/structure." }
  ]
};

window.TEST_BANK_QUESTIONS['aids_ds'] = window.TEST_BANK_QUESTIONS['cs_ds'];
window.TEST_BANK_QUESTIONS['aids_prog'] = window.TEST_BANK_QUESTIONS['cs_cpp'];
window.TEST_BANK_QUESTIONS['aids_oop'] = window.TEST_BANK_QUESTIONS['cs_java1'] = [
  { q: "Which keyword is used in Java to implement inheritance between classes?", options: ["implements", "extends", "inherits", "super"], correct: 1, explanation: "The 'extends' keyword is used to inherit a class." },
  { q: "What does 'polymorphism' refer to in Object-Oriented Programming?", options: ["Hiding internal class variables", "The ability of an object to take on many forms", "Combining variables and functions inside a class", "Copying methods from one object to another"], correct: 1, explanation: "Polymorphism allows objects to behave differently depending on their class types." }
];
window.TEST_BANK_QUESTIONS['aids_db'] = window.TEST_BANK_QUESTIONS['cs_db'];
